### ISSUE TITLE
Mods die in spectator in world=nether

### ISSUE THREAD

**Issue by vinceingithub** [kakduman/Acorn#32] opened 2020-06-29 18:57 UTC
**Describe the bug**

When mods go into spectator mode in the end/nether we'll fall into the void and die because we don't have fly perms for gamemode=spectator in the end/nether.

**Expected behavior**

If you are mod and go into spec in the end or nether you should fall into the void and die.

**To Reproduce**

1. Be Mod
2. Go into gamemode spectator while in the end or nether
3. Die and see error

**Additional context**
Add any other context about the problem here. Most players can ignore this section.

**Comment by Pemigrade** [comment] 2020-06-30 22:04
Should be fixed with the addition of ExtraContents. Restart required. If the problem is not fixed after the next restart, this issue will be reopened.

**Comment by Pemigrade** [comment] 2020-07-01 06:40
Issue is not fixed.

**Closed** 2024-08-12 20:23 UTC
Labels: Medium Priority, Bug Report
